#!/bin/bash

if [[ -z "$1" ]]; then
	test=$(rg -g "*_spec.lua" --files ./lua/tests | fzf)
	if [[ -z "$test" ]]; then
		echo "No test provided"
		exit 1
	fi
else
	test="$1"
fi

nvim --noplugin -u scripts/runtime.vim --headless -c "PlenaryBustedFile ${test}"
