name: CI

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: update
        run: |
          sudo apt-get update

      - name: install fzf
        run: |
          sudo apt-get install -y fzf

      - name: install plenary.nvim
        uses: actions/checkout@v4
        with:
          repository: nvim-lua/plenary.nvim
          path: plenary.nvim

      - name: install luacov
        run: |
          sudo apt-get install -y luarocks
          sudo luarocks install luacov
          sudo luarocks install luacov-console

      - name: use neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.9.0

      - name: run tests
        run: |
          nvim --version
          NOCLEAN=1 make testcov

      - name: upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: luacov.report.out, luacov.stats.out
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  linting:
    runs-on: ubuntu-latest
    name: linting

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: update
        run: |
          sudo apt-get update

      - name: install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: run luacheck
        run: |
          sudo make lint

      - name: run stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check lua
